# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.grpc.python.pb import service_pb2 as src_dot_grpc_dot_python_dot_pb_dot_service__pb2


class GalaxyGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.pingNode = channel.unary_unary(
                '/GalaxyGrpc/pingNode',
                request_serializer=src_dot_grpc_dot_python_dot_pb_dot_service__pb2.NodePing.SerializeToString,
                response_deserializer=src_dot_grpc_dot_python_dot_pb_dot_service__pb2.NodePong.FromString,
                )
        self.getAllNodeStatus = channel.unary_unary(
                '/GalaxyGrpc/getAllNodeStatus',
                request_serializer=src_dot_grpc_dot_python_dot_pb_dot_service__pb2.Empty.SerializeToString,
                response_deserializer=src_dot_grpc_dot_python_dot_pb_dot_service__pb2.AllNodeStatus.FromString,
                )
        self.ExcuteNodeCommand = channel.unary_unary(
                '/GalaxyGrpc/ExcuteNodeCommand',
                request_serializer=src_dot_grpc_dot_python_dot_pb_dot_service__pb2.ReqNodeCommand.SerializeToString,
                response_deserializer=src_dot_grpc_dot_python_dot_pb_dot_service__pb2.ResNodeCommand.FromString,
                )


class GalaxyGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def pingNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAllNodeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExcuteNodeCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GalaxyGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'pingNode': grpc.unary_unary_rpc_method_handler(
                    servicer.pingNode,
                    request_deserializer=src_dot_grpc_dot_python_dot_pb_dot_service__pb2.NodePing.FromString,
                    response_serializer=src_dot_grpc_dot_python_dot_pb_dot_service__pb2.NodePong.SerializeToString,
            ),
            'getAllNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.getAllNodeStatus,
                    request_deserializer=src_dot_grpc_dot_python_dot_pb_dot_service__pb2.Empty.FromString,
                    response_serializer=src_dot_grpc_dot_python_dot_pb_dot_service__pb2.AllNodeStatus.SerializeToString,
            ),
            'ExcuteNodeCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExcuteNodeCommand,
                    request_deserializer=src_dot_grpc_dot_python_dot_pb_dot_service__pb2.ReqNodeCommand.FromString,
                    response_serializer=src_dot_grpc_dot_python_dot_pb_dot_service__pb2.ResNodeCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GalaxyGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GalaxyGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def pingNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GalaxyGrpc/pingNode',
            src_dot_grpc_dot_python_dot_pb_dot_service__pb2.NodePing.SerializeToString,
            src_dot_grpc_dot_python_dot_pb_dot_service__pb2.NodePong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAllNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GalaxyGrpc/getAllNodeStatus',
            src_dot_grpc_dot_python_dot_pb_dot_service__pb2.Empty.SerializeToString,
            src_dot_grpc_dot_python_dot_pb_dot_service__pb2.AllNodeStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExcuteNodeCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GalaxyGrpc/ExcuteNodeCommand',
            src_dot_grpc_dot_python_dot_pb_dot_service__pb2.ReqNodeCommand.SerializeToString,
            src_dot_grpc_dot_python_dot_pb_dot_service__pb2.ResNodeCommand.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
