# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc/python/pb/service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n src/grpc/python/pb/service.proto\"\x07\n\x05\x45mpty\"=\n\x08NodePing\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06server\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\"\x1b\n\x08NodePong\x12\x0f\n\x07message\x18\x01 \x01(\t\":\n\x04Node\x12\x16\n\x06server\x18\x01 \x01(\tR\x06server\x12\x1a\n\x08username\x18\x02 \x01(\tR\x08username\"?\n\nNodeStatus\x12\x19\n\x04node\x18\x01 \x01(\x0b\x32\x05.NodeR\x04node\x12\x16\n\x06status\x18\x02 \x01(\tR\x06status\"*\n\rAllNodeStatus\x12\x19\n\x04node\x18\x01 \x03(\x0b\x32\x0b.NodeStatus\"E\n\x0eReqNodeCommand\x12\x19\n\x04node\x18\x01 \x01(\x0b\x32\x05.NodeR\x04node\x12\x18\n\x07\x63ommand\x18\x02 \x01(\tR\x07\x63ommand\"&\n\x0eResNodeCommand\x12\x14\n\x07message\x18\x01 \x01(\tR\x03msg2\x97\x01\n\nGalaxyGrpc\x12\"\n\x08pingNode\x12\t.NodePing\x1a\t.NodePong\"\x00\x12,\n\x10getAllNodeStatus\x12\x06.Empty\x1a\x0e.AllNodeStatus\"\x00\x12\x37\n\x11\x45xcuteNodeCommand\x12\x0f.ReqNodeCommand\x1a\x0f.ResNodeCommand\"\x00\x42\nZ\x08/;clientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.grpc.python.pb.service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010/;client'
  _EMPTY._serialized_start=36
  _EMPTY._serialized_end=43
  _NODEPING._serialized_start=45
  _NODEPING._serialized_end=106
  _NODEPONG._serialized_start=108
  _NODEPONG._serialized_end=135
  _NODE._serialized_start=137
  _NODE._serialized_end=195
  _NODESTATUS._serialized_start=197
  _NODESTATUS._serialized_end=260
  _ALLNODESTATUS._serialized_start=262
  _ALLNODESTATUS._serialized_end=304
  _REQNODECOMMAND._serialized_start=306
  _REQNODECOMMAND._serialized_end=375
  _RESNODECOMMAND._serialized_start=377
  _RESNODECOMMAND._serialized_end=415
  _GALAXYGRPC._serialized_start=418
  _GALAXYGRPC._serialized_end=569
# @@protoc_insertion_point(module_scope)
